buildx to create container image and load in local registry. (#1938)
`--platform linux/amd64,linux/arm64 --load` does not work because local docker registry can host different architectures

`$(GOOS)/$(GOARCH)` would also not work because causes an error pulling ubi image from redhat

```
ERROR: failed to solve: registry.access.redhat.com/ubi9/ubi-micro:latest: no match for platform in manifest: not found
```

Signed-off-by: pjuarezd <pjuarezd@users.noreply.github.com>